on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image to dev
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/printscript-ui:latest-dev
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}

      - name: Build and push Docker image to prod
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/printscript-ui:latest-prod
          build-args: |
            VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            BACKEND_URL=${{ secrets.BACKEND_URL_PROD }}
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key for DEV
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEV }}

      - name: Run Script on Azure VM
        run: |
          ssh -v -o StrictHostKeyChecking=no sonpipe@${{ secrets.VM_DEV_IP }} << 'ENDSSH'
          cd micro-infra
          docker compose -f docker-compose.dev.yml down ui-service
          docker compose -f docker-compose.dev.yml pull ui-service
          docker compose -f docker-compose.dev.yml up -d ui-service
          ENDSSH

      - name: Add SSH key for production
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_STABLE }}

      - name: Run Script on Azure VM Stable
        run: |
          ssh -v -o StrictHostKeyChecking=no sonpipe@${{ secrets.VM_STABLE_IP }} << 'ENDSSH'
          cd micro-infra
          docker compose down ui-service
          docker compose pull ui-service
          docker compose up -d ui-service
          ENDSSH