on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image with memory limit
        run: |
          docker buildx build --memory=2g \
                               --build-arg VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }} \
                               --build-arg VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }} \
                               --build-arg BACKEND_URL=localhost:5173/api/snippet \
                               -t ghcr.io/${{ github.repository_owner }}/printscript-ui:latest \
                               .
          docker push ghcr.io/${{ github.repository_owner }}/printscript-ui:latest
