on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push front-end image for master
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/printscript-ui:latest
          secrets: |
            FRONTEND_ENV=${{ secrets.FRONTEND_ENV }}
            API_URL=${{ secrets.API_URL }}
            BACKEND_URL=localhost:5173/api/snippet

